---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ default .Release.Namespace .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    env: {{ .Values.env }}
    version: v{{ default .Chart.Version .Values.image.tag }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
      env: {{ .Values.env }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        env: {{ .Values.env }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: GREETING
            value: {{default "Merhaba Helm!" .Values.environment.GREETING | quote }}
        command:
            - "/bin/sh"
            - "-c"
            - "while true; do { echo -e 'HTTP/1.1 200 OK\r\n'; echo $GREETING; } | nc -l -p  8080; done"
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
        resources:
          {{- toYaml .Values.resources | nindent 12 }}